import "./globals.css"
import { cookies } from "next/headers"
import { RootLayoutClient } from "@/components/root-layout-client"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const themeClass = (await cookies()).get("theme")?.value ?? "theme-violet"
  const mode = (await cookies()).get("theme-mode")?.value as "light" | "dark" | "system" ?? "system"

  return (
    <RootLayoutClient themeClass={themeClass} themeMode={mode}>
      {children}
    </RootLayoutClient>
  )
}
